version: '3.6'
services:

  database:
    image: postgres:14
    container_name: aerpaw-db
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pg_data/data:${PGDATA}
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:1
    container_name: aerpaw-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS_DIR}:/etc/ssl:ro